### ISSUE TITLE
Errors Compiling

### ISSUE THREAD

**Issue by OYKOKO** [kindahl/libkeepass#1]
## FAST Response is appreciated I am trying to use this library to get into my keypass database using permutations of my last remembered password(s)

I installed all the dependencies and even went back in the time with commits and it didn't compiled this build log is me building the latest version.

mkdir -p build/debug/obj
g++ -MMD -g -DDEBUG -std=c++11 -Wall -Wextra -Werror -c -o build/debug/obj/stream.o src/stream.cc
In file included from src/stream.hh:28:0,
                 from src/stream.cc:19:
src/util.hh:50:39: error: ‘vector’ in namespace ‘std’ does not name a template type
 inline bool indirect_equal(const std::vector<T>& v0,
                                       ^~~~~~
src/util.hh:50:45: error: expected ‘,’ or ‘...’ before ‘<’ token
 inline bool indirect_equal(const std::vector<T>& v0,
                                             ^
src/util.hh: In function ‘bool keepass::indirect_equal(int)’:
src/util.hh:52:21: error: ‘v0’ was not declared in this scope
   return std::equal(v0.begin(), v0.end(), v1.begin(),
                     ^~
src/util.hh:52:43: error: ‘v1’ was not declared in this scope
   return std::equal(v0.begin(), v0.end(), v1.begin(),
                                           ^~
src/util.hh: At global scope:
src/util.hh:82:34: error: ‘vector’ in namespace ‘std’ does not name a template type
 template <typename T, const std::vector<std::shared_ptr<T>>& (T::*F)() const>
                                  ^~~~~~
src/util.hh: 100:13: error: expected unqualified-id before ‘time_to_str’
 std::string time_to_str(const std::time_t& time);
             ^~~~~~~~~~~
src/util.hh: 100:13: error: expected ‘>’ before ‘time_to_str’
src/util.hh: 100:49: error: expected unqualified-id before ‘;’ token
 std::string time_to_str(const std::time_t& time);
                                                 ^
In file included from src/stream.cc:19:0:
src/stream.hh\:103:8: error: ‘vector’ in namespace ‘std’ does not name a template type
   std::vector<char> block_;
        ^~~~~~
src/stream.hh:173:8: error: ‘vector’ in namespace ‘std’ does not name a template type
   std::vector<char> buffer_;
        ^~~~~~
src/stream.cc: In member function ‘std::array<unsigned char, 32ul> keepass::hashed_basic_streambuf::GetBlockHash() const’:
src/stream.cc:35:26: error: ‘block_’ was not declared in this scope
   SHA256_Update(&sha256, block_.data(), block_.size());
                          ^~~~~~
src/stream.cc: In member function ‘virtual int keepass::hashed_istreambuf::underflow()’:
src/stream.cc:52:5: error: ‘block_’ was not declared in this scope
     block_.clear();
     ^~~~~~
src/stream.cc: In member function ‘bool keepass::hashed_ostreambuf::FlushBlock()’:
src/stream.cc:82:23: error: ‘block_’ was not declared in this scope
   header.block_hash = block_.empty() ? kEmptyHash : GetBlockHash();
                       ^~~~~~
src/stream.cc: In member function ‘virtual int keepass::hashed_ostreambuf::overflow(int)’:
src/stream.cc:103:3: error: ‘block_’ was not declared in this scope
   block_.push_back(static_cast<char>(c));
   ^~~~~~
src/stream.cc: In member function ‘virtual int keepass::hashed_ostreambuf::sync()’:
src/stream.cc:114:8: error: ‘block_’ was not declared in this scope
   if (!block_.empty()) {
        ^~~~~~
src/stream.cc: In member function ‘bool keepass::gzip_ostreambuf::WriteOutput(bool)’:
src/stream.cc:201:24: error: ‘buffer_’ was not declared in this scope
   z_stream_.avail_in = buffer_.size();
                        ^~~~~~~
src/stream.cc: In member function ‘virtual int keepass::gzip_ostreambuf::overflow(int)’:
src/stream.cc:234:3: error: ‘buffer_’ was not declared in this scope
   buffer_.push_back(static_cast<char>(c));
   ^~~~~~~
Makefile:23: recipe for target 'build/debug/obj/stream.o' failed
make: *** [build/debug/obj/stream.o] Error 1

Using Debian 9.3 I didn't compiled any build tool myself. I don't know what I am doing wrong.
Also I tried replacing -std=c++11 with different versions.

(For some reason inserting the log as code make it appear as one paragraph of text)

**Comment by kindahl** [comment]
It appears there was a few issues when I tried to compile with GCC 7.2.0. I have added a couple of includes that was missing from src/util.hh and also disabled the `implicit-fallthrough` warning introduced with GCC 7.

Can you pull latest and see if that version works for you?

**Comment by OYKOKO** [comment]
Thanks it compiles! I needed to install googletest manually using [this](https://stackoverflow.com/questions/13513905/how-to-setup-googletest-as-a-shared-library-on-linux) answer in case anyone got stuck like I did.
